### ISSUE TITLE
Move Cache into .icon-factory

### ISSUE THREAD

**Issue by jpgilchrist** [quasarframework/icongenie#57]
I would like to have the dev/build output cached in git so that the files aren't generated in various situations, such as: continuous integration

Also, for my use cases it will be common to switch back and forth between `quasar dev` and `quasar build -m cordova -T (adnroid|ios]) [--debug -s]` and various forms of `quasar build. So, I'd rather it not run compression when I switch back and forth.

**Comment by nothingismagick** [comment]
This has been open for a while. I think @rstoenescu needs to give his feedback here.

**Comment by rstoenescu** [comment]
1. Move cache folder to `/.icon-genie-cache`. Also alleviates one problem that happens at the moment: any yarn install/uninstall removes the cache folder so IconGenie ends up having to recreate the icons. Downside is that the project folder becomes more cluttered -- wish Windows would fade out folders starting with a dot so that it would offer a tip to the user that "you shouldn't care about this folder".

2. Prompt the user: "Do you want the icon cache folder in your GIT repo?" -- and add it to .gitignore file if it's the case.

**Comment by rstoenescu** [comment]
Closed it by mistake. Sorry.

**Comment by nothingismagick** [comment]
Ok, will do the recfactor. It will make it into the next patch release.

**Comment by rstoenescu** [comment]
This will be obsolete with the complete rewrite of Icon Genie v2.
